### ISSUE TITLE
tiles have capacity

### ISSUE THREAD

**Issue by Le5tes** [Le5tes/hex-ops#11]
As a player,
So that my opponent can't smoosh all their units onto one tile making it impregnable,
tiles should have limited capacity for units

**Comment by LarsFin** [comment]
./modes/tile.js
*defining capacity*
```
class Tile {
  constructor(capacity = 6){
  	this.CAPACITY = capacity;
  	this.units = [];
  };
```
*ensuring capacity can't be breached*
```
canAccomodate(unit){
  	return (this.spaceLeft() >= unit.size);
  };

  spaceLeft() {
    return (this.CAPACITY - this._unitSizes().sum());
  };
```
See ./spec/tileSpec.js "Tile" & "Tile#canAccomodate" for respective tests
