### ISSUE TITLE
A tile can assign a unit to defend

### ISSUE THREAD

**Issue by Le5tes** [Le5tes/hex-ops#15]
As a player,
So that I can send an unwilling unit to defend my land,
A tile should randomly assign one of it's units as a defender when attacked.

**Comment by LarsFin** [comment]
./models/tile.js
```
defend(mod = Math){
  	return (this.units[mod.floor(mod.random() * this.units.length)]);
  };
```
See ./spec/tileSpec.js "Tile#defend" for tests
