### ISSUE TITLE
Tiles have co-ordinates

### ISSUE THREAD

**Issue by Le5tes** [Le5tes/hex-ops#8]
As a player
So that I can instruct my units to go to a particular tile
I want tiles to know their position

**Comment by LarsFin** [comment]
./models/tile.js
```
constructor(capacity = 6, x = 0, y = 0){
    this.CAPACITY = capacity;
    this.units = [];
    this.x = x;
    this.y = y;
  };
```
See ./spec/tileSpec.js "Tile" for tests
